import{a as f,S as v,i as m}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const b=document.querySelector(".form");b.addEventListener("submit",w);const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),n=document.querySelector(".is-hidden");n.addEventListener("click",S);const L="11329962-6436ba51ddb58bb96deed169a";let g,d,u;f.defaults.baseURL="https://pixabay.com/api";async function w(e){g=1,e.preventDefault(),c.innerHTML="",l.classList.add("is-visible"),n.classList.remove("is-visible");const t=e.currentTarget;d=t.elements.searchTerm.value;try{let r=await h(d);if(r.total===0){x();return}else p(r),u=new v(".gallery a"),u.refresh()}catch(r){y(r.message)}finally{t.reset()}}async function S(){l.classList.add("is-visible");try{let e=await h(d);p(e),u.refresh();let r=c.querySelector("li").getBoundingClientRect();scrollBy({top:r.height*2+48,behavior:"smooth"})}catch(e){y(e.message)}}function p(e){n.classList.remove("is-visible");let t="";for(const r of e.hits)t+=q(r);l.classList.remove("is-visible"),c.insertAdjacentHTML("beforeend",t),M(e.totalHits)}function M(e){c.querySelectorAll("li").length<e?n.classList.add("is-visible"):P()}async function h(e){const t=new URLSearchParams({key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:g}),r=await f.get(`/?${t}`);return g++,r.data}function q({webformatURL:e,largeImageURL:t,tags:r,likes:a,views:s,comments:o,downloads:i}){return`<li class="gallery-item">
        <a class="gallery-link" href="${t}">
            <img class="gallery-image" src="${e}" alt="${r}" />
        </a>
        <div class="gallery-details">
            <div class="detail"><img class="gallery-logo" src="like.png" /> <p class="gallery-text">${a}</p></div>
            <div class="detail"><img class="gallery-logo" src="viev.png" /> <p class="gallery-text">${s}</p></div>
            <div class="detail"><img class="gallery-logo" src="comment.png" /> <p class="gallery-text">${o}</p></div>
            <div class="detail"><img class="gallery-logo" src="download.png" /> <p class="gallery-text">${i}</p></div>
        </div>
    </li>`}function x(){m.show({position:"topRight",messageColor:"white",iconUrl:"error.svg",iconColor:"white",color:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!"}),l.classList.remove("is-visible")}function y(e){m.show({position:"topRight",messageColor:"white",iconUrl:"attention.png",iconColor:"white",color:"#EF4040",message:e}),l.classList.remove("is-visible")}function P(){m.show({position:"topRight",messageColor:"white",iconUrl:"fin.png",iconColor:"white",color:"#4E75FF",message:"We're sorry, but you've reached the end of search results."})}
//# sourceMappingURL=commonHelpers.js.map
