import{a as n,S as d,i as u}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const m=document.querySelector(".form");m.addEventListener("submit",f);const c=document.querySelector(".gallery"),i=document.querySelector(".loader"),p="11329962-6436ba51ddb58bb96deed169a";let g;n.defaults.baseURL="https://pixabay.com/api";async function f(o){g=1,o.preventDefault(),c.innerHTML="",i.classList.add("is-visible");const s=o.currentTarget,l=s.elements.searchTerm.value;try{const t=await y(l);if(t.totalHits===0)v();else{let e="";for(const a of t.hits)e+=h(a);i.classList.remove("is-visible"),c.insertAdjacentHTML("beforeend",e),new d(".gallery a").refresh()}}catch(t){console.log(t)}finally{s.reset()}}async function y(o){const s=new URLSearchParams({key:p,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:g});return(await n.get(`/?${s}`)).data}function h({webformatURL:o,largeImageURL:s,tags:l,likes:t,views:e,comments:r,downloads:a}){return`<li class="gallery-item">
        <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${o}" alt="${l}" />
        </a>
        <div class="gallery-details">
            <div class="detail"><img class="gallery-logo" src="like.png" /> <p class="gallery-text">${t}</p></div>
            <div class="detail"><img class="gallery-logo" src="viev.png" /> <p class="gallery-text">${e}</p></div>
            <div class="detail"><img class="gallery-logo" src="comment.png" /> <p class="gallery-text">${r}</p></div>
            <div class="detail"><img class="gallery-logo" src="download.png" /> <p class="gallery-text">${a}</p></div>
        </div>
    </li>`}function v(){u.show({position:"topRight",messageColor:"white",iconUrl:"error.svg",iconColor:"white",color:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!"}),i.classList.remove("is-visible")}
//# sourceMappingURL=commonHelpers.js.map
